---
version: "3"
services:
  little-link:
    build: .
    image: littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=TechProber
      - META_DESCRIPTION=TechProber Link page
      - META_AUTHOR=TechProber
      - THEME=Dark
      - FAVICON_URL=https://avatars.githubusercontent.com/u/93818962?s=400&u=13fa537dbfd8bf0715c17109c4d8d6e23bbc359a&v=4
      - AVATAR_URL=https://avatars.githubusercontent.com/u/93818962?s=400&u=13fa537dbfd8bf0715c17109c4d8d6e23bbc359a&v=4
      - AVATAR_2X_URL=https://avatars.githubusercontent.com/u/93818962?s=400&u=13fa537dbfd8bf0715c17109c4d8d6e23bbc359a&v=4
      - AVATAR_ALT=TechProber Profile Pic
      - NAME=TechProber
      - BIO=Hey! Just a place where you can connect with me!
      - HUGO=https://github.com/TechProber
      - GITHUB=https://github.com/TechProber
      - DISCORD=https://discord.gg/95K3J3a4
      - TELEGRAM=https://t.me/joinchat/7AG3aEQ5I00wY2Q5
      - FOOTER=Thanks for stopping by!
      # - TWITTER=
      # - INSTAGRAM=
      # - YOUTUBE=
      # - TWITCH=
      # - TIKTOK=
      # - KIT=
      # - FACEBOOK=
      # - FACEBOOK_MESSENGER=
      # - PRODUCT_HUNT=
      # - SNAPCHAT=
      # - SPOTIFY=
      # - REDDIT=
      # - MEDIUM=
      # - PINTEREST=
      # - EMAIL_ALT=
      # - SOUND_CLOUD=
      # - FIGMA=
      # - TUMBLR=
      # - STEAM=
      # - VIMEO=
      # - GOODREADS=
      # - SKOOB=
    ports:
      - 3000:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
