---
version: "3"
services:
  little-link:
    image: hikariai/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Hikariai
      - META_DESCRIPTION=Kevin Yu Link page
      - META_AUTHOR=Kevin Yu
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - AVATAR_ALT=Kevin Yu Profile Pic
      - NAME=Hikariai
      - BIO=Hey! Just a place where you can connect with me!
      - WORDPRESS=https://www.hikariai.net
      - GITHUB=https://github.com/yqlbu
      - DISCORD=https://discord.gg/95K3J3a4
      - EMAIL=kevinyu211@yahoo.com
      # - TWITTER=https://twitter.com/TechnoTimLive
      # - INSTAGRAM=https://www.instagram.com/techno.tim
      # - YOUTUBE=https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
      # - TWITCH=https://www.twitch.tv/technotim/
      # - TIKTOK=https://www.tiktok.com/@technotim
      # - KIT=https://kit.co/TechnoTim
      # - FACEBOOK=https://facebook.com
      # - FACEBOOK_MESSENGER=https://facebook.com
      # - LINKED_IN=https://linkedin.com
      # - PRODUCT_HUNT=https://www.producthunt.com/
      # - SNAPCHAT=https://www.snapchat.com/
      # - SPOTIFY=https://www.spotify.com/
      # - REDDIT=https://www.reddit.com/
      # - MEDIUM=https://medium.com
      # - PINTEREST=https://www.pinterest.com/
      # - EMAIL_ALT=you@example.com
      # - SOUND_CLOUD=https://souncloud.com
      # - FIGMA=https://figma.com
      # - TELEGRAM=https://telegram.org/
      # - TUMBLR=https://www.tumblr.com/
      # - STEAM=https://steamcommunity.com/
      # - VIMEO=https://vimeo.com/
      # - GOODREADS=https://www.goodreads.com/
      # - SKOOB=https://www.skoob.com.br/
      - FOOTER=Thanks for stopping by!
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
